name: Flutter

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master" ]

jobs:
  createRelease:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Set up job
        run: |
          TAG_NAME=$(date +'%Y%m%d%H%M%S')
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path

      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle

      - name: Upload APK
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: andorid-Ble_Doorlock_Opener.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  publishAPK:
    runs-on: ubuntu-latest
    needs: [buildAndroid, createRelease]
    steps:
      - name: Set up job
        run: |
          echo "RELEASE_UPLOAD_URL=${{ needs.createRelease.outputs.release_upload_url }}" >> $GITHUB_ENV

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: andorid-Ble_Doorlock_Opener.apk
          path: build/app/outputs/flutter-apk/

      - name: Publish APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.RELEASE_UPLOAD_URL }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: Android-Ble_Doorlock_Opener.apk
          asset_content_type: application/vnd.android.package-archive

  buildIos:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path

      - run: flutter pub get
      - run: flutter build ios --release --no-codesign

      - name: Zip IOS App
        run: zip -r build/ios/iphoneos/Runner.zip build/ios/iphoneos/Runner.app

      - name: Upload IOS-APP
        uses: actions/upload-artifact@v4
        with:
          name: IOS-Runner-Ble_Doorlock_Opener.zip
          path: build/ios/iphoneos/Runner.zip

      - name: Build IPA
        run: flutter build ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: IOS-App-Ble_Doorlock_Opener-app.ipa
          path: build/ios/ipa/ble_doorlock_opener.ipa

  publishIOS:
    runs-on: macos-latest
    needs: [buildIos, createRelease]
    steps:
      - name: Set up job
        run: |
          echo "RELEASE_UPLOAD_URL=${{ needs.createRelease.outputs.release_upload_url }}" >> $GITHUB_ENV

      - name: Download IOS App Zip
        uses: actions/download-artifact@v4
        with:
          name: IOS-Runner-Ble_Doorlock_Opener.zip
          path: build/ios/iphoneos/

      - name: Publish IOS App Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.RELEASE_UPLOAD_URL }}
          asset_path: build/ios/iphoneos/Runner.zip
          asset_name: IOS-Runner-Ble_Doorlock_Opener.zip
          asset_content_type: application/zip

      - name: Download IPA
        uses: actions/download-artifact@v4
        with:
          name: IOS-App-Ble_Doorlock_Opener-app.ipa
          path: build/ios/ipa/

      - name: Publish IPA
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.RELEASE_UPLOAD_URL }}
          asset_path: build/ios/ipa/ble_doorlock_opener.ipa
          asset_name: IOS-App-Ble_Doorlock_Opener-app.ipa
          asset_content_type: application/zip
